name: quransenja
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

#-------------------------PACKAGE-----------------------#
dependencies:
  flutter:
    sdk: flutter

  # utility package
  logger: ^2.6.1
  intl: ^0.20.2
  dio: ^5.8.0+1

  # icons
  cupertino_icons: ^1.0.8
  iconsax_plus: ^1.0.0

  # font
  google_fonts: ^6.3.0

  # state management
  get: ^4.7.2
  get_storage: ^2.1.1

  # general
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #-------------------------LOCAL ASSETS-----------------------#
  assets:
    - assets/images/
    - assets/icons/
